---
title: "filtering for PCA"
author: "Tatenda Musimwa"
date: "November 16, 2018"
output: html_document
---
```{r}
library(tidyverse)
```

```{r} 
geno <- read.csv("./geno.csv")
geno #data inspection
```

# Calculation before filtering
# R(AG) Y(CT) S(CG) W(AT) K(GT) M(AC) N(NA)
```{r}

geno_remove_na <- filter(geno,!is.na(alleles)) #remove SNPs with NA in "alleles"
geno_sep <- separate(geno_remove_na,alleles,c("allele1","allele2"),sep = "/") #seperate "alleles" to "allele1" & "allele2"
geno_sep
geno_count <- geno_sep %>% unite(string,-(1:12),sep = "",remove = T) %>% #unite all SNP columns together
  mutate(count.A=str_count(string,"A"), # count the number of "A" in "string"
         count.C=str_count(string,"C"),
         count.G=str_count(string, "G"),
         count.T=str_count(string,"T"),
         count.R=str_count(string,"R"),
         count.Y=str_count(string,"Y"),
         count.S=str_count(string,"S"),
         count.W=str_count(string,"W"),
         count.K=str_count(string,"K"),
         count.M=str_count(string,"M"),
         count.N=str_count(string,"N")
  )


for (i in 1:55103) # loop by row
{
  if (geno_count[i,2] == "A") # if allele1 = A, then allele1_count = count_A
  {
    geno_count$allele1_c[i] = geno_count$count.A[i] + (geno_count$count.R[i] + geno_count$count.W[i] + geno_count$count.M[i])/2
  } 
  else
    {
    if (geno_count[i,2] == "G")
      {
      geno_count$allele1_c[i] = geno_count$count.G[i] +(geno_count$count.R[i] + geno_count$count.S[i] + geno_count$count.K[i])/2
      } 
      else
        {
        if (geno_count[i,2] == "C")
          {
           geno_count$allele1_c[i] = geno_count$count.C[i] +(geno_count$count.Y[i] + geno_count$count.S[i] +geno_count$count.M[i])/2
          } 
          else 
            {
            geno_count$allele1_c[i] = geno_count$count.T[i] +(geno_count$count.Y[i] + geno_count$count.W[i] +geno_count$count.K[i])/2
            }
        }
    }
}

for (i in 1:55103) 
{
  if (is.na(geno_count[i,3])) # if allele2 = NA, allele2_count = 0
  {
     geno_count$allele2_c[i] = 0
  }
  else
    {
      if(geno_count[i,3] == "A")
      {
        geno_count$allele2_c[i] = geno_count$count.A[i] + (geno_count$count.R[i] + geno_count$count.W[i] + geno_count$count.M[i])/2
      }
    else
    {
        if (geno_count[i,3] == "G")
          {
          geno_count$allele2_c[i] = geno_count$count.G[i] +(geno_count$count.R[i] + geno_count$count.S[i] + geno_count$count.K[i])/2
          } 
        else
        {
          if (geno_count[i,3] == "C")
            {
            geno_count$allele2_c[i] = geno_count$count.C[i] +(geno_count$count.Y[i] + geno_count$count.S[i] +geno_count$count.M[i])/2
          } 
          else
          {
            geno_count$allele2_c[i] = geno_count$count.T[i] +(geno_count$count.Y[i] + geno_count$count.W[i] +geno_count$count.K[i])/2
          }
        }
    }
    }
}

```

#Filtering
```{r}
geno_count$allele_c_sum <- geno_count$allele1_c + geno_count$allele2_c
summary(geno_count$allele_c_sum)

geno_count$allele1_f <- geno_count$allele1_c/geno_count$allele_c_sum
geno_count$allele2_f <- geno_count$allele2_c/geno_count$allele_c_sum

summary(geno_count$allele1_f)
summary(geno_count$allele2_f)

filter <- filter(geno_count,count.N < 86 ) %>% #filter by missing value (854 * 0.1 = 85.4)
  filter(allele2_f > 0.1) %>% # filter by minor allele frequency
  filter(allele1_f >0.1)
```

####Attempting to figure out filtering by position map interval